### ISSUE TITLE
Argument of type 'FacebookLoginWeb' is not assignable to parameter of type 'WebPlugin'

### ISSUE THREAD

**Issue by rodrigo-fonseca** [rdlabo/capacitor-facebook-login#18]
I'm getting this error:

> Argument of type 'FacebookLoginWeb' is not assignable to parameter of type 'WebPlugin'. Types have separate declarations of a private property 'addWindowListener'.

when:

```
import { registerWebPlugin } from '@capacitor/core';
registerWebPlugin(FacebookLogin);
```

Can you help me? ;)

**Comment by rdlabo** [comment]
I think it is because it is different from the version of the main body. Please try again as we released the latest version today.
Thanks.

**Comment by ghost** [comment]
I am getting same error. please help me.

**Comment by yigitbacakoglu** [comment]
Same error

**Comment by rodrigo-fonseca** [comment]
> I think it is because it is different from the version of the main body. Please try again as we released the latest version today.
> Thanks.

I'm with the newest version and still happen :(

> Argument of type 'FacebookLoginWeb' is not assignable to parameter of type 'WebPlugin'.
>   Property 'removeAllListeners' is missing in type 'FacebookLoginWeb' but required in type 'WebPlugin'.ts(2345)

ps: The error is not the same

**Comment by martindongo** [comment]
> I think it is because it is different from the version of the main body. Please try again as we released the latest version today.
> Thanks.

I'm getting this error in my ionic project:

Argument of type 'FacebookLoginWeb' is not assignable to parameter of type 'WebPlugin'.
  Types have separate declarations of a private property 'addWindowListener'.ts(2345)

"@capacitor/core": "2.1.2"
"@rdlabo/capacitor-facebook-login": "^2.0.3"

Any ideas to fix it?
thanks in advance

**Comment by rdlabo** [comment]
@martindongo  add `@ts-ignore` , please. I plan to investigate again when I have time, but sorry for I am busy now.

```
// @ts-ignore
registerWebPlugin(FacebookLogin);
```
