### ISSUE TITLE
registerWebPlugin throws error

### ISSUE THREAD

**Issue by jonathon-m** [rdlabo/capacitor-facebook-login#6]
When attempting to register the web plugin, as per the instructions, I get this error:

`Argument of type 'FacebookLoginWeb' is not assignable to parameter of type 'WebPlugin'.
  Types have separate declarations of a private property 'addWindowListener'.`

The plugin was working until recently, so this could be due to a capacitor update. 

Thanks!

**Comment by rdlabo** [comment]
This is capacitor version Issue. I fixed by @rdlabo/capacitor-facebook-login@1.0.8
Please update.

**Comment by 7freaks-otte** [comment]
I just faced the same error again after upgrading to capacitor 1.2.0.

It seems that even with `@capacitor/core: "latest"` npm does not recognize that the latest version is already installed in `node_modules/@capacitor/core` and installs it again into `node_modules/@rdlabo/capacitor-facebook-login/node_modules/@capacitor/core` which results in the "separate declarations error".

My first solution was to just delete the `@capacitor/core` directory within your plugin but that only works until you use `npm install` again.

The second solution was to remove your plugin and my `package-lock.json` and reinstall the plugin. This will probably work until I update Capacitor again.

Any idea on how to fix this permanently? I have the same issue with my own plugin and just don't know how to teach npm to not install a separate version of `@capacitor/core` after an upgrade other than upgrading my plugin with every capacitor upgrade to use the exact capacitor version numbers. (Just moving my capacitor core dependency to peerDependencies in package.json did not work either)

**Comment by atmosuwiryo** [comment]
I'm using version 1.0.9.

I solved mine by:
```npm uninstall @capacitor/core @capacior/cli```
```npm install --save @capacitor/core@1.2.0 @capacitor/cli@1.2.0```

The reason I choose capacitor V.1.2.0 is by this lines found in my project's package.lock.json
```
    "@rdlabo/capacitor-facebook-login": {
      "version": "1.0.9",
      "resolved": "https://registry.npmjs.org/@rdlabo/capacitor-facebook-login/-/capacitor-facebook-login-1.0.9.tgz",
      "integrity": "sha512-VvomfX8zuf4bay+mQ6t7+X0T1KEp2pW2XVyorAbdTUZ4YqIfNE8FJDyH8JWlAbO63jo1hUKoSZWJGafX605mLg==",
      "requires": {
        "@capacitor/core": "^1.2.0"
      },
```
I've try capacitor V.1.2.1(latest version at current time) previously and still have this error. Using capacitor V.1.2.0 works on me.
